# Copyright (C) 2026 - present, Carrier Team

# Aufruf:   docker compose up
#           docker compose exec carrier bash
#           docker compose down

include:
  - path: ../backend/compose.yml

services:
  carrier:
    image: juergenzimmermann/carrier:2026.4.1-hardened
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_healthy
      keycloak:
        condition: service_healthy

    stop_signal: SIGINT
    ports:
      - published: 8000
        target: 8000
    volumes:
      - type: bind
        source: app.toml
        target: /opt/app/.venv/lib/python3.14/site-packages/carrier/config/resources/app.toml
        read_only: true
      - type: bind
        source: ../../../log
        target: /opt/app/log
      - type: bind
        source: ../../../src/carrier/config/resources/tls/key.pem
        target: /opt/app/.venv/lib/python3.14/site-packages/carrier/config/resources/tls/key.pem
        read_only: true
      - type: bind
        source: ../../../src/carrier/config/resources/tls/certificate.crt
        target: /opt/app/.venv/lib/python3.14/site-packages/carrier/config/resources/tls/certificate.crt
        read_only: true
    env_file: .env
    networks: [acme-network]
    hostname: carrier
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G

networks:
  acme-network:
    name: acme-network
